name: EC2 Describe OIDC Test
on:
    push:
        branches:
          - main
    workflow_dispatch:
jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
          - name: chekout repo
            uses: actions/checkout@v4
          - name: aws configure
            uses: aws-actions/configure-aws-credentials@v4
            with:
                role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
                aws-region: ap-south-1
          - name: List EC2
            run: aws ec2 describe-instances