name: Terraform CI pipeline

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: dev
    env:
        role_arn: ${{ secrets.ROLE_ARN}}
    defaults:
      run:
        working-directory: terraform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt

      - name: Terraform Plan
        run: terraform plan -var="role_arn=${{ secrets.ROLE_ARN }}"

      - name: Terraform Apply
        run: terraform apply -var="role_arn=${{ secrets.ROLE_ARN }}" --auto-approve
