name: Terraform CI Pipeline
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  AWS_OIDC_ROLE: ${{ secrets.AWS_OIDC_ROLE }}
  AWS_REGION: ${{ vars.AWS_REGION }}
  TERRAFORM_ROLE_ARN: ${{ secrets.ROLE_ARN}}
defaults:
  run:
    working-directory: terraform
    shell: bash

jobs:
  Terraform-Setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials (via OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_OIDC_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION}}
      - name: Terraform Initialize
        run: terraform init
      - name: Terraform Format
        run: terraform fmt
      - name: Terraform Plan
        run: terraform plan -var="role_arn=${{ secrets.ROLE_ARN }}" -out=tfplan
      - name: Upload tfplan artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: ./infra/tfplan