name: Terraform CI pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
  pull-requests: write
env:
      TERRAFORM_VERSION: ${{ vars.TERRAFORM_VERSION }}
      ROLE_ARN: ${{ secrets.ROLE_ARN }}
      AWS_REGION: ${{ vars.AWS_REGION }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}
          role-session-name: GitHub-OIDC-Action
          role-duration-seconds: 900

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ vars.TERRAFORM_VERSION }}

      - name: Terraform Init
        run: |
          terraform -v
          terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Format Check
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan -var="role_arn=${{ secrets.ROLE_ARN }}" -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: terraform/tfplan
      - name: Terraform Apply
        run: terraform apply "tfplan"